### ISSUE TITLE
Problem when one player holds a key

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/PolyPong#1]
This will basically block other players.... 

One easy fix (maybe not perfect) is to have the listener `on release`, though it might still be some competition... Maybe threads?

Anyway, this should not be a problem in the distributed version of the game....

**Comment by jakhog** [comment]
Haha, I like that you've tried already 👍 

It's a keyboard/onpressed issue. Anyways, we should do it like in the pong. Set flags when buttons are pressed and released, and then move as long as it is pressed. I guess this is what you ment...

The way it works now we rely on the keyboard event to be sent multiple times (which is dependent on the user settings). 

Small fix, but that was enough for today 😝
